name: ci
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        js: [[node, 22], [node, 24], [bun, latest]]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: ${{matrix.js[1]}}
        if: ${{matrix.js[0] == 'node'}}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{matrix.js[1]}}
        if: ${{matrix.js[0] == 'bun'}}
      - run: make lint test
        if: ${{matrix.js[0] == 'node'}}
      - run: bun install && bun test
        if: ${{matrix.js[0] == 'bun'}}
